### ISSUE TITLE
[Bug]: error: TypeError: Cannot read properties of undefined 

### ISSUE THREAD

**Issue by benbensimpson** [iobroker-community-adapters/ioBroker.tankerkoenig#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Heute update auf 3.3.0 gemacht seitdem steht alles auf 0 adapter ist grün im log steht:
`<html>
<body>

[ Adapter V:3.3.0 writeState ] error: TypeError: Cannot read properties of undefined (reading 'toString') stack: TypeError: Cannot read properties of undefined (reading 'toString') at Tankerkoenig.writeState (/opt/iobroker/node_modules/iobroker.tankerkoenig/build/main.js:865:42) at async Tankerkoenig.requestData (/opt/iobroker/node_modules/iobroker.tankerkoenig/build/main.js:117:11) at async Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.tankerkoenig/build/main.js:74:13)
--

</body>
</html>`

### Adapter version

3.3.0

### Environment

```markdown
- Node:v16.19.0
- npm:8.19.3
- JS-Controller:4.0.24
- Operating system:Debian 11
```

**Comment by Diginix** [comment]
Same here with 3.3.0 on each instance start I got this error:

```
2022-12-30 09:37:00.194 - info: tankerkoenig.0 (685640) starting. Version 3.3.0 in /opt/iobroker/node_modules/iobroker.tankerkoenig, node: v16.19.0, js-controller: 4.0.24
2022-12-30 09:37:00.228 - info: tankerkoenig.0 (685640) Adapter is already in daemon mode
2022-12-30 09:37:00.229 - info: tankerkoenig.0 (685640) Sync time set to 10 minutes or 600000 ms
2022-12-30 09:37:01.559 - info: tankerkoenig.0 (685640) Start first request
2022-12-30 09:37:01.904 - error: tankerkoenig.0 (685640) [ Adapter V:3.3.0 writeState ] error: TypeError: Cannot read properties of undefined (reading 'toString') stack: TypeError: Cannot read properties of undefined (reading 'toString')
    at Tankerkoenig.writeState (/opt/iobroker/node_modules/iobroker.tankerkoenig/src/main.ts:1033:35)
    at Tankerkoenig.requestData (/opt/iobroker/node_modules/iobroker.tankerkoenig/src/main.ts:156:6)
    at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.tankerkoenig/src/main.ts:96:7)

```

Until 3.2.5 all was fine.

**Comment by xXBJXx** [comment]
After the update, you have to go to the UI again and then click on 
![image](https://user-images.githubusercontent.com/32600934/210060779-e2cc4099-8861-4404-8da1-3eac1aab1328.png)
and copy the ID once again, so that the data is taken over correctly, by clicking on add and save.

**Comment by Diginix** [comment]
Ok, seams to solve this issue but now I got thsi for every station:
`State value to set for "tankerkoenig.0.stations.7.postCode" has to be type "number" but received type "string"`

**Comment by xXBJXx** [comment]
Delete the state one time and restart the will regenerate newly created. The type has changed to number

**Comment by benbensimpson** [comment]
Von github 3.3.1 installiert alles wieder ok
